### ISSUE TITLE
GDScript bug: Native class "KraImporter" not found.

### ISSUE THREAD

**Issue by Aniwer** [2shady4u/godot-krita-importer#3]
When i download this from AssetLib，I encountered the following problem：
```
  modules/gdscript/gdscript_compiler.cpp:121 - GDScript bug: Native class "KraImporter" not found.
  res://addons/godot-krita-importer/krita_import_plugin.gd:56 - Compile Error: Identifier not found: KraImporter
  res://addons/godot-krita-importer/godot-krita-importer.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/godot-krita-importer/godot-krita-importer.gd" with error "Compilation failed". (User)
```
Can you help me😭

**Comment by Aniwer** [comment]
I get it, I need to delete link libraries for other platforms

**Comment by timkrief** [comment]
It did not work for me, I'm stuck with the same issue.

**Comment by timkrief** [comment]
It's seems like I'm using 4.2.0 and it's only working on 4.2.1

**Comment by 2shady4u** [comment]
Hello @timkrief 

GDExtension isn't really good at preserving compatibility between minor Godot versions :/
Nothing I can really do about that unfortunately...

**Comment by timkrief** [comment]
Hi! Yes I saw that in the documentation, no worries, I just upgraded to 4.2.2 since they were maintenance release with no known issues but I wasn't able to run it on 4.2.2 either. Finally I tried it on 4.2.1 and it works! It's a really good plugin, saves a lot of time!
